name = "Steve SMP S5 Reloaded"
author = "Steveplays28"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a14486d997209b49d90beba7a0d0d620c5b75b917f575c615ee60b0f45797d3"

[versions]
minecraft = "1.19.2"
quilt = "0.17.10"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "/global_packs/required_data"
